### ISSUE TITLE
Final Grade

### ISSUE THREAD

**Issue by quuu** [dannoprojects/pwp-capstones#1]
## Rubric Score
 
### Criteria 1: Valid Python Code
* _Score Level:_ 1
* _Comment(s):_ Code included runs with errors.

TomeRater.py runs fine because it contains only class declarations and no real test cases, but after running populate.py, lots of errors in the code gets pointed out. 

Small Error - typo in the name of `most_read_book()` because the user included an `s` at the end of the method.

Larger Error - Learner mis-used the `max()` function by not passing in a comparable type for the second argument. 

Learner should have tested the test cases before submitting to make sure the project specifications were all completely finished.
 
### Criteria 2: Implementation of Project Requirements
* _Score Level:_ 4
* _Comment(s):_ Code produces between 100% of functions and classes required of it and calls them in an appropriate order.

### Criteria 3: Software Architecture
* _Score Level:_ 4
* _Comment(s):_ Code is separated into distinct classes and functions each which are invoked for their own purpose.
 
### Criteria 4: Uses Python Language Features
* _Score Level:_ 4
* _Comment(s):_ Code uses language features appropriately. If a task can be solved with a Python language feature, it is.

Good use of iterators, nested calculations such as `return str([book for book in self.books.keys() if book.get_average_rating() == top_rated])` in `highest_rated_book(self)`, and `format()`.
 
### Overall Score: 13/16

Learner has a really good grasp of Python fundamentals and even some Python advanced tricks such as the above mentioned line of code by writing loops in-line. Learner should check over his/her work more as when I ran the test cases attached to the project, it crashed on `most_read_book()`. 

Learner should take more care and spend a little more time testing out all the functionality.

Great use of comments that really explained what each function should be doing without having to read the actual code.

**Comment by dannoprojects** [comment]
@quuu Thanks for the review.  Should I post updated code to cover the errors or is this my final score?  I can find no rubric beyond submit code.

**Comment by quuu** [comment]
@dannoprojects Hey! You don't need to post updated code. You can if you want, but you still got a passing grade that will earn you the certificate! The rubric is only for graders, but if you want to find out how to get those 3 points back, look at the file `populate.py` and uncomment the test cases... then run `populate.py`.

**Comment by dannoprojects** [comment]
@quuu Perfect.  That is the information that I needed.  I'll take a look at the test cases and review my code to understand my errors.   Thanks again.
